/** Interface text for the Pray page, in English and Spanish. */

export const T = {
  en: {
    eyebrow: "Pray",
    h1: { "100": "100 days of prayer for every place in LA and OC", "365": "A year of prayer for every place in LA and OC" },
    intro: { "100": "One place a day, from the Antelope Valley to San Clemente. Pray through it, mark it done, and watch the map fill in. Tap any area on the map to jump to its day.",
             "365": "One neighborhood or town for each day of the year, from the Antelope Valley to San Clemente. Tap any area on the map to jump to its day." },
    saved: "Your progress is saved on this device.",
    progress: (t: number) => ["You've prayed for ", ` of ${t} days`] as const,
    dayOf: (n: number, t: number) => `Day ${n} of ${t}`,
    plans: { "100": "100 days", "365": "365 days" },
    who: "Who's here", through: "Pray through", pray: "Pray", partOf: "Part of",
    verseNote: "Read the passage on bible.com (ESV)",
    more: "More to pray about", moreSub: "Optional · 7 topics",
    prayed: "I prayed for this", prayedDone: "Prayed",
    allDays: (t: number) => `All ${t} days`, sections: (n: number) => `${n} sections`,
    whole: "Whole map", back: "Zoom to today", legend: "Already prayed for", today: "Go to today",
    kinds: { a: "Whole region", r: "Region", p: "Neighborhoods", q: "Neighborhood or town", f: "Focus" },
    focusPrefix: "Focus: ",
    county: { LA: "Los Angeles County", OC: "Orange County" }, countyShort: { LA: "LA County", OC: "OC" },
    both: "Los Angeles and Orange counties", region: "Region", focusDay: "Focus day", areas: (n: number) => `${n} areas`,
    secStart: "Day 1 · All of LA and OC", secEnd: (n: number) => `Day ${n} · No place left`, secBoth: "Across both counties",
    pDay: (m: string) => `Pray for ${m}: that God would move and work here, and raise up disciples of Jesus among the people who live here.`,
    pWho: (pp: string) => `Pray that God would move and work among ${pp}, and raise up disciples of Jesus who make disciples of others.`,
    pChurch: "Pray that God would move and work through believers and churches across LA and OC, and raise up disciples who make disciples.",
    everywhere: "LA and OC", tipDay: "Day", days: "Days",
    prev: "Previous day", next: "Next day", mapLabel: "Map of Los Angeles and Orange counties by ZIP code area, with today's place in yellow",
    locale: "en-US",
  },
  es: {
    eyebrow: "Orar",
    h1: { "100": "100 días de oración por cada lugar de LA y OC", "365": "Un año de oración por cada lugar de LA y OC" },
    intro: { "100": "Un lugar cada día, desde el Valle de Antelope hasta San Clemente. Ora por él, márcalo y mira cómo se llena el mapa. Toca cualquier área del mapa para ir a su día.",
             "365": "Un vecindario o pueblo para cada día del año, desde el Valle de Antelope hasta San Clemente. Toca cualquier área del mapa para ir a su día." },
    saved: "Tu progreso se guarda en este dispositivo.",
    progress: (t: number) => ['Has orado por ', ` de ${t} días`] as const,
    dayOf: (n: number, t: number) => `Día ${n} de ${t}`,
    plans: { "100": "100 días", "365": "365 días" },
    who: "Quiénes viven aquí", through: "Ora por", pray: "Ora", partOf: "Parte de",
    verseNote: "Lee el pasaje en bible.com (NVI)",
    more: "Más motivos de oración", moreSub: "Opcional · 7 temas",
    prayed: "Oré por esto", prayedDone: "Oré",
    allDays: (t: number) => `Los ${t} días`, sections: (n: number) => `${n} secciones`,
    whole: "Mapa completo", back: "Volver al día", legend: "Ya oraste por aquí", today: "Ir a hoy",
    kinds: { a: "Toda la región", r: "Región", p: "Vecindarios", q: "Vecindario o pueblo", f: "Enfoque" },
    focusPrefix: "Enfoque: ",
    county: { LA: "Condado de Los Ángeles", OC: "Condado de Orange" }, countyShort: { LA: "Condado de LA", OC: "OC" },
    both: "Condados de Los Ángeles y Orange", region: "Región", focusDay: "Día de enfoque", areas: (n: number) => `${n} áreas`,
    secStart: "Día 1 · Todo LA y OC", secEnd: (n: number) => `Día ${n} · Que no quede ningún lugar`, secBoth: "En ambos condados",
    pDay: (m: string) => `Ora por ${m}: que Dios se mueva y obre aquí, y levante discípulos de Jesús entre las personas que viven aquí.`,
    pWho: (pp: string) => `Ora para que Dios se mueva y obre entre ${pp}, y levante discípulos de Jesús que hagan discípulos de otros.`,
    pChurch: "Ora para que Dios se mueva y obre por medio de los creyentes y las iglesias de LA y OC, y levante discípulos que hagan discípulos.",
    everywhere: "LA y OC", tipDay: "Día", days: "Días",
    prev: "Día anterior", next: "Día siguiente", mapLabel: "Mapa de los condados de Los Ángeles y Orange por código postal, con el lugar de hoy en amarillo",
    locale: "es-US",
  },
};

export type Strings = (typeof T)['en'];
