// Generates src/components/map-data.ts from us-atlas county boundaries.
// LA County (06037) + Orange County (06059), mainland only, projected to a
// 1000x1000 SVG box. Also projects a set of named places so the map can
// show the network as nodes. Run: node scripts/build-map.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import * as topojson from 'topojson-client';
import { geoMercator, geoPath, geoArea } from 'd3-geo';

const root = resolve(import.meta.dirname, '..');
const topo = JSON.parse(readFileSync(resolve(root, 'node_modules/us-atlas/counties-10m.json')));
const counties = topojson.feature(topo, topo.objects.counties).features;
const neighbors = ['06111', '06029', '06071', '06065', '06073']; // Ventura, Kern, San Bernardino, Riverside, San Diego

const mainland = (f) => {
  if (f.geometry.type !== 'MultiPolygon') return f;
  // keep only the largest ring (drops Catalina, San Clemente, etc.)
  const polys = f.geometry.coordinates.map((c) => ({ c, a: geoArea({ type: 'Polygon', coordinates: c }) }));
  polys.sort((x, y) => y.a - x.a);
  return { ...f, geometry: { type: 'Polygon', coordinates: polys[0].c } };
};

const la = mainland(counties.find((c) => c.id === '06037'));
const oc = mainland(counties.find((c) => c.id === '06059'));
const ctx = counties.filter((c) => neighbors.includes(c.id)).map(mainland);

const W = 1000, H = 1000;
const projection = geoMercator().fitExtent(
  [[60, 60], [W - 60, H - 60]],
  { type: 'FeatureCollection', features: [la, oc] },
);
const path = geoPath(projection);

const places = [
  // id, label, lon, lat, hub, size(1-3)
  ['dtla', 'Downtown LA', -118.2437, 34.0522, 'la', 3],
  ['santa-monica', 'Santa Monica', -118.4912, 34.0195, 'la', 1],
  ['pasadena', 'Pasadena', -118.1445, 34.1478, 'la', 2],
  ['long-beach', 'Long Beach', -118.1937, 33.7701, 'la', 2],
  ['van-nuys', 'San Fernando Valley', -118.4490, 34.1867, 'la', 2],
  ['torrance', 'South Bay', -118.3406, 33.8358, 'la', 1],
  ['pomona', 'Pomona', -117.7500, 34.0551, 'la', 1],
  ['el-monte', 'San Gabriel Valley', -118.0276, 34.0686, 'la', 1],
  ['south-la', 'South LA', -118.2870, 33.9600, 'la', 1],
  ['santa-clarita', 'Santa Clarita', -118.5426, 34.3917, 'la', 1],
  ['lancaster', 'Antelope Valley', -118.1542, 34.6868, 'la', 1],
  ['anaheim', 'Anaheim', -117.9143, 33.8366, 'oc', 2],
  ['santa-ana', 'Santa Ana', -117.8678, 33.7455, 'oc', 3],
  ['irvine', 'Irvine', -117.8265, 33.6846, 'oc', 2],
  ['huntington', 'Huntington Beach', -117.9992, 33.6595, 'oc', 1],
  ['fullerton', 'Fullerton', -117.9243, 33.8704, 'oc', 1],
  ['westminster', 'Westminster', -117.9940, 33.7514, 'oc', 1],
  ['mission-viejo', 'Mission Viejo', -117.6580, 33.6000, 'oc', 1],
  ['san-clemente', 'San Clemente', -117.6120, 33.4270, 'oc', 1],
  ['newport', 'Newport Beach', -117.9289, 33.6189, 'oc', 1],
].map(([id, label, lon, lat, hub, size]) => {
  const [x, y] = projection([lon, lat]);
  return { id, label, hub, size, x: +x.toFixed(1), y: +y.toFixed(1) };
});

const centroid = (f) => path.centroid(f).map((n) => +n.toFixed(1));

const out = `// GENERATED by scripts/build-map.mjs — do not edit by hand.
export const MAP_W = ${W};
export const MAP_H = ${H};
export const counties = {
  la: { path: ${JSON.stringify(path(la))}, centroid: ${JSON.stringify(centroid(la))} },
  oc: { path: ${JSON.stringify(path(oc))}, centroid: ${JSON.stringify(centroid(oc))} },
};
export const context = ${JSON.stringify(ctx.map((c) => path(c)))};
export type Place = { id: string; label: string; hub: 'la' | 'oc'; size: number; x: number; y: number };
export const places: Place[] = ${JSON.stringify(places)};
`;
writeFileSync(resolve(root, 'src/components/map-data.ts'), out);
console.log('wrote map-data.ts', out.length, 'bytes');
